import type { Actor, Check, Outcome } from './types';
import { ACTORS } from './types';
import type { LiveStep } from './live-deactivation';

export type Result = { check: Check; actual: Record<Actor, string> };

const HEADERS: Record<Actor, string> = {
    anon: 'anon',
    inactive: 'inactive (deactivated)',
    OPERATOR: 'OPERATOR',
    MANAGER: 'MANAGER',
    SUPERADMIN: 'SUPERADMIN',
};

export const mismatches = (results: Result[]) =>
    results.flatMap((r) =>
        ACTORS.filter((a) => r.actual[a] !== r.check.expected[a]).map((a) => ({
            id: r.check.id,
            actor: a,
            expected: r.check.expected[a] as Outcome,
            actual: r.actual[a],
        })),
    );

/** Таблица для консоли: строка на проверку, галочка или расхождение в каждой ячейке. */
export function consoleTable(results: Result[]): string {
    const idWidth = Math.max(...results.map((r) => r.check.id.length));
    const lines = [
        `${'check'.padEnd(idWidth)}  ${ACTORS.map((a) => a.padEnd(22)).join(' ')}`,
        '-'.repeat(idWidth + 2 + ACTORS.length * 23),
    ];
    for (const r of results) {
        const cells = ACTORS.map((a) => {
            const got = r.actual[a];
            const text = got === r.check.expected[a] ? `ok  ${got}` : `!!  ${got} (want ${r.check.expected[a]})`;
            return text.padEnd(22);
        });
        lines.push(`${r.check.id.padEnd(idWidth)}  ${cells.join(' ')}`);
    }
    return lines.join('\n');
}

/**
 * Отчёт для заказчика. Английский: это то, что видит посетитель
 * репозитория (CLAUDE.md, раздел "Язык"). Ячейка - фактический ответ API;
 * совпало с ожиданием - галочка, нет - крест и ожидание рядом.
 */
export function markdownReport(
    results: Result[],
    live: { steps: LiveStep[]; passed: boolean },
    notes: string[],
): string {
    const bad = mismatches(results);
    const total = results.length * ACTORS.length;
    const out: string[] = [];

    out.push('# Policy matrix report', '');
    out.push(
        'Real API requests, made with real sessions: `supabase-js` signs in with a password (a genuine JWT), ' +
            'talks to PostgREST and the Storage API, and the results are compared with the expected outcome. ' +
            'Generated by `npm run test:api` (`tests/api/`). Do not edit by hand.',
        '',
    );
    out.push(`- Generated: ${new Date().toISOString()}`);
    out.push(`- Checks: ${results.length}, cells: ${total}, mismatches: **${bad.length}**`);
    out.push(`- Live deactivation scenario: **${live.passed ? 'passed' : 'FAILED'}**`, '');

    out.push('## How to read the tables', '');
    out.push(
        '| Outcome | Meaning |',
        '|---|---|',
        '| `allowed` | the request worked and returned rows or had an effect |',
        '| `empty` | a read worked but returned nothing: RLS filtered every row (no error) |',
        '| `zero_rows` | an UPDATE/DELETE worked but touched 0 rows: the policy `USING` did not let the row through (no error) |',
        '| `error:42501` | permission denied: no grant, or a policy `WITH CHECK` / trigger refused the write |',
        '| `error:P0001` | a business rule in a trigger or RPC refused the action |',
        '| `error:23505` | unique constraint violated |',
        '',
        'Actors: **anon** - no sign-in, publishable key only. **inactive** - a genuinely signed-in operator whose `staff.is_active` is `false`. ' +
            '**OPERATOR**, **MANAGER**, **SUPERADMIN** - the three staff roles.',
        '',
        'Cells: ✅ matches the expectation, ❌ shows what came back and what was expected.',
        '',
    );

    if (bad.length > 0) {
        out.push('## Mismatches', '', '| Check | Actor | Expected | Got |', '|---|---|---|---|');
        for (const m of bad) out.push(`| \`${m.id}\` | ${m.actor} | \`${m.expected}\` | \`${m.actual}\` |`);
        out.push('');
    }

    const groups = [...new Set(results.map((r) => r.check.group))];
    for (const group of groups) {
        out.push(`## ${group}`, '');
        out.push(`| Check | ${ACTORS.map((a) => HEADERS[a]).join(' | ')} | Why |`);
        out.push(`|---|${ACTORS.map(() => '---').join('|')}|---|`);
        for (const r of results.filter((x) => x.check.group === group)) {
            const cells = ACTORS.map((a) =>
                r.actual[a] === r.check.expected[a]
                    ? `✅ \`${r.actual[a]}\``
                    : `❌ \`${r.actual[a]}\` (expected \`${r.check.expected[a]}\`)`,
            );
            out.push(`| ${r.check.description} | ${cells.join(' | ')} | ${r.check.why} |`);
        }
        out.push('');
    }

    out.push('## A deactivated employee loses access immediately', '');
    out.push(
        'The role lives in the `staff` table, not in the JWT. One session (one token) is used before and after ' +
            'the employee is deactivated; the token is never re-issued.',
        '',
        '| Step | Result | |',
        '|---|---|---|',
    );
    for (const s of live.steps) out.push(`| ${s.label} | \`${s.result}\` | ${s.ok ? '✅' : '❌'} |`);
    out.push('');

    if (notes.length > 0) {
        out.push('## Data left behind by the run', '');
        for (const n of notes) out.push(`- ${n}`);
        out.push('');
    }
    return out.join('\n');
}
